# coding: utf-8
import ROOT
canvas = ROOT.TCanvas("canvas", "canvas")
rtfile = ROOT.TFile("fitPtZlep1.root")
histdy = rtfile.Get("DY/ptl1_mm")
histdy.SetFillColor(ROOT.kYellow)
canvas.Update()
bkhist = rtfile.Get("bkgd/ptl1_mm")
bkhist
bkhist.SetFillColor(ROOT.kGray)
canvas.Update()
data_obs = rtfile.Get("data_obs")
data_hist = data_obs.Get("ptl1_mm")
data_hist.SetMarkerStyle(1)
canvas.Update()
hist_stack = ROOT.THStack("stack", "stack")
hist_stack.Add(bkhist)
hist_stack.Add(histdy)
hist_stack.Draw()
canvas.Update()
data_hist.Draw("e1 same")
canvas.Update()
print "DY yield", histdy.Integral()
print "bkgd yield", bkhist.Integral()
print "data yield", data_hist.Integral()
